インクリメンタルサーチ
TakumiKATAOKA/chat-space pull request #9
Opened 2019-03-10 07:54 UTC by TakumiKATAOKA

#what
インクリメンタルサーチの実装
#why
検索時のユーザビリティを高めるため

2019-03-10 07:58 UTC, yuki-uchida requested changes

2019-03-10 07:58 UTC, yuki-uchida commented on app/assets/javascripts/user.js
> +  function appendUser(user){
userの何をどこに追加しているのかがわからないので、分かるような名前にしましょう

2019-03-11 05:44 UTC, TakumiKATAOKA commented on app/assets/javascripts/user.js
> +  function appendUser(user){
appendUserをappendUserSearchResultに変更

2019-03-11 05:47 UTC, miyagit commented on app/assets/javascripts/user.js
> +        $(this).parent().remove();
ここいんでんとおかしいですね。

2019-03-11 05:47 UTC, miyagit commented on app/controllers/users_controller.rb
> +    @users=User.where("name LIKE(?)","%#{params[:keyword]}%")
ログインユーザーを含めないようにしましょう。

2019-03-11 05:49 UTC, TakumiKATAOKA commented on app/assets/javascripts/user.js
> +        $(this).parent().remove();
修正しました

2019-03-11 06:42 UTC, TOMARUMARU commented on app/assets/javascripts/user.js
> +  function removeGroupUser(user_id,user_name){
このfunctionの中のインデント見直しましょう

2019-03-11 06:42 UTC, TOMARUMARU commented on app/controllers/users_controller.rb
> +    @users=User.where("name LIKE(?)","%#{params[:keyword]}%").where.not(name: current_user.name)
スペースも意識しましょう
```@users = User.where```

2019-03-11 06:57 UTC, TakumiKATAOKA commented on app/assets/javascripts/user.js
> +  function removeGroupUser(user_id,user_name){
修正しました。

2019-03-11 06:57 UTC, TakumiKATAOKA commented on app/controllers/users_controller.rb
> +    @users=User.where("name LIKE(?)","%#{params[:keyword]}%").where.not(name: current_user.name)
修正しました。

2019-03-11 07:01 UTC, TOMARUMARU approved these changes
LGTM

2019-03-11 07:02 UTC, merged